name: Build
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Gem name to build"
        type: string
        required: true
      version:
        description: "Gem version to build"
        type: string
        required: true
permissions:
  packages: write
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      is-extension: ${{ steps.info.outputs.is-extension }}
    steps:
      - uses: actions/checkout@v6
      - name: Info
        id: info
        env:
          NAME: ${{ inputs.name }}
          VERSION: ${{ inputs.version }}
        run: |
          set -x
          # "gem fetch" may be failed if this workflow is submitted by
          # rubygems.org's webhook because the target gem isn't
          # registered on rubygems.org yet.
          n_tries=0
          while ! gem fetch ${NAME}:${VERSION}; do
            n_tries=$[n_tries + 1]
            if [ ${n_tries} -gt 5 ]; then
              exit 1
            fi
            sleep 10
          done
          gem specification ${NAME}-${VERSION}.gem > spec.yaml
          is_extension=$(ruby -e 'puts !Gem::Specification.from_yaml(ARGF).extensions.empty?' spec.yaml)
          echo "is-extension=${is_extension}" >> ${GITHUB_OUTPUT}
  build:
    name: Build
    needs:
      - check
    if: needs.check.outputs.is-extension
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: release
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker image
        run: |
          docker compose build build
      - name: Build binary gem
        run: |
          docker compose run --rm build ${{ inputs.name }} ${{ inputs.version }}
      - uses: actions/upload-artifact@v6
        with:
          name: gem
          path: ${{ inputs.name }}-${{ inputs.version }}-*.gem
      - name: Prepare
        run: |
          mkdir -p ~/.gem
          cat <<CREDENTIALS > ~/.gem/credentials
          ---
          :cloudsmith: Bearer ${{ secrets.CLOUDSMITH_API_KEY }}
          CREDENTIALS
          chmod go-rwx ~/.gem/credentials
      - name: Push
        run: |
          gem push \
            --key cloudsmith \
            --host https://ruby.cloudsmith.io/rubygems-precompiled-gems/ruby-4-0-amd64-ubuntu-24-04 \
            ${{ inputs.name }}-${{ inputs.version }}-*.gem
