name: Build ${{ inputs.name }} ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Gem name to build"
        type: string
        required: true
      version:
        description: "Gem version to build"
        type: string
        required: true
permissions:
  packages: write
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      need-build: ${{ steps.info.outputs.need-build }}
    steps:
      - name: Show summary
        run: |
          url="https://rubygems.org/gems/${{ inputs.name }}/versions/${{ inputs.version }}"
          echo "* RubyGems: ${url}" | tee -a  ${GITHUB_STEP_SUMMARY}
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Info
        id: info
        env:
          NAME: ${{ inputs.name }}
          VERSION: ${{ inputs.version }}
        run: |
          # "gem fetch" may be failed if this workflow is submitted by
          # rubygems.org's webhook because the target gem isn't
          # registered on rubygems.org yet.
          n_tries=0
          while ! gem fetch --platform=ruby ${NAME}:${VERSION}; do
            n_tries=$[n_tries + 1]
            if [ ${n_tries} -gt 5 ]; then
              exit 1
            fi
            sleep 60
          done
          gem specification ${NAME}-${VERSION}.gem > spec.yaml
          is_extension=$(ruby -e 'puts !Gem::Specification.from_yaml(ARGF).extensions.empty?' spec.yaml)
          is_pushable=$(ruby -e 'puts !Gem::Specification.from_yaml(ARGF).metadata.key?("allowed_push_host")' spec.yaml)
          if [ "${is_extension}" = "true" ] && [ "${is_pushable}" = "true" ]; then
            echo "need-build=true" >> ${GITHUB_OUTPUT}
          else
            echo "need-build=false" >> ${GITHUB_OUTPUT}
          fi
  build:
    name: Build
    needs:
      - check
    if: needs.check.outputs.need-build == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: release
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker image
        run: |
          docker compose build build
      - name: Build binary gem
        run: |
          docker compose run --rm build ${{ inputs.name }} ${{ inputs.version }}
      - uses: actions/upload-artifact@v6
        with:
          name: gem
          path: ${{ inputs.name }}-${{ inputs.version }}-*.gem
      - name: Prepare
        run: |
          mkdir -p ~/.gem
          cat <<CREDENTIALS > ~/.gem/credentials
          ---
          :cloudsmith: Bearer ${{ secrets.CLOUDSMITH_API_KEY }}
          CREDENTIALS
          chmod go-rwx ~/.gem/credentials
      - name: Push
        run: |
          gem push \
            --key cloudsmith \
            --host https://ruby.cloudsmith.io/rubygems-precompiled-gems/ruby-4-0-amd64-ubuntu-24-04 \
            ${{ inputs.name }}-${{ inputs.version }}-*.gem
